# This is a basic workflow to help you get started with Actions

name: Ansible Lint

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Make function for getting Pip versions of packages
        run: get_pip_ver() { curl -s https://pypi.org/pypi/$@/json | jq ".info.version" | tr -d '"'; }
        shell: bash

      - name: Set the value of Ansible-Lints Version (to build cache key)
        run: |
          echo "ANSIBLE_LINT_VERSION=$(get_pip_ver ansible-lint)" >> $GITHUB_ENV
        shell: bash
          
      - name: Set the value of YamlLints Version (to build cache key)
        run: |
          echo "YAMLLINT_VERSION=$(get_pip_ver yamllint)" >> $GITHUB_ENV
        shell: bash

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: pip-${{ env.ANSIBLE_LINT_VERSION }}-${{ env.YAMLLINT_VERSION }}
          restore-keys: |
            pip-${{ env.ANSIBLE_LINT_VERSION }}-${{ env.YAMLLINT_VERSION }}
      
      - name: Check working directory
        run: ls
        
      - name: Install Ansible-Lint and Yamllint
        run: pip install ansible-lint yamllint ansible
        shell: bash

      - name: Run Ansible-Lint
        run: ansible-lint --version
        shell: bash
    
      - name: Run Ansible-Lint
        run: ansible-lint
        shell: bash
        
